[2025-09-09 21:55:52,988: INFO: Phase_01_data_ingestion: >>>>>> Data Ingestion Phase started <<<<<<]
[2025-09-09 21:55:52,989: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-09 21:55:52,989: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-09 21:55:52,989: INFO: common: created directory at: ./artifacts]
[2025-09-09 21:55:52,990: INFO: common: created directory at: ./artifacts/data_ingestion]
[2025-09-09 21:55:52,990: INFO: data_ingestion: Downloading file from :[https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing] into :[artifacts/data_ingestion/data.zip]]
[2025-09-09 21:56:14,330: INFO: data_ingestion: File :[artifacts/data_ingestion/data.zip] has been downloaded successfully.]
[2025-09-09 21:56:14,330: INFO: data_ingestion: Unzipping file :[artifacts/data_ingestion/data.zip] into dir :[artifacts/data_ingestion]]
[2025-09-09 21:56:15,833: INFO: data_ingestion: Unzipping completed successfully. and data is available at :[artifacts/data_ingestion]]
[2025-09-09 21:56:15,833: INFO: Phase_01_data_ingestion: >>>>>> Data Ingestion Phase completed <<<<<<

x==========x]
[2025-09-09 21:59:34,027: INFO: main: >>>>>> Data Ingestion Phase started <<<<<<]
[2025-09-09 21:59:34,027: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-09 21:59:34,028: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-09 21:59:34,028: INFO: common: created directory at: ./artifacts]
[2025-09-09 21:59:34,028: INFO: common: created directory at: ./artifacts/data_ingestion]
[2025-09-09 21:59:34,028: INFO: data_ingestion: Downloading file from :[https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing] into :[artifacts/data_ingestion/data.zip]]
[2025-09-10 02:47:14,638: INFO: main: >>>>>> Data Ingestion Phase started <<<<<<]
[2025-09-10 02:47:14,640: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-10 02:47:14,642: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-10 02:47:14,642: INFO: common: created directory at: ./artifacts]
[2025-09-10 02:47:14,643: INFO: common: created directory at: ./artifacts/data_ingestion]
[2025-09-10 02:47:14,643: INFO: data_ingestion: Downloading file from :[https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing] into :[artifacts/data_ingestion/data.zip]]
[2025-09-10 02:47:34,587: INFO: data_ingestion: File :[artifacts/data_ingestion/data.zip] has been downloaded successfully.]
[2025-09-10 02:47:34,587: INFO: data_ingestion: Unzipping file :[artifacts/data_ingestion/data.zip] into dir :[artifacts/data_ingestion]]
[2025-09-10 02:47:36,047: INFO: data_ingestion: Unzipping completed successfully. and data is available at :[artifacts/data_ingestion]]
[2025-09-10 02:47:36,047: INFO: main: >>>>>> Data Ingestion Phase completed <<<<<<

x==========x]
[2025-09-10 02:47:36,048: INFO: main: >>>>>> Prepare Base Model Phase started <<<<<<]
[2025-09-10 02:47:36,049: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-10 02:47:36,050: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-10 02:47:36,050: INFO: common: created directory at: ./artifacts]
[2025-09-10 02:47:36,050: INFO: common: created directory at: ./artifacts/prepare_base_model]
[2025-09-10 02:47:36,318: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-10 02:47:36,396: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-10 02:47:36,454: INFO: main: >>>>>> Prepare Base Model Phase completed <<<<<<

x==========x]
[2025-09-10 03:11:23,484: INFO: main: >>>>>> Data Ingestion Phase started <<<<<<]
[2025-09-10 03:11:23,486: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-10 03:11:23,487: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-10 03:11:23,487: INFO: common: created directory at: ./artifacts]
[2025-09-10 03:11:23,487: INFO: common: created directory at: ./artifacts/data_ingestion]
[2025-09-10 03:11:23,487: INFO: data_ingestion: Downloading file from :[https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing] into :[artifacts/data_ingestion/data.zip]]
[2025-09-10 03:11:45,676: INFO: data_ingestion: File :[artifacts/data_ingestion/data.zip] has been downloaded successfully.]
[2025-09-10 03:11:45,677: INFO: data_ingestion: Unzipping file :[artifacts/data_ingestion/data.zip] into dir :[artifacts/data_ingestion]]
[2025-09-10 03:11:46,925: INFO: data_ingestion: Unzipping completed successfully. and data is available at :[artifacts/data_ingestion]]
[2025-09-10 03:11:46,926: INFO: main: >>>>>> Data Ingestion Phase completed <<<<<<

x==========x]
[2025-09-10 03:11:46,926: INFO: main: >>>>>> Prepare Base Model Phase started <<<<<<]
[2025-09-10 03:11:46,927: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-10 03:11:46,928: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-10 03:11:46,928: INFO: common: created directory at: ./artifacts]
[2025-09-10 03:11:46,928: INFO: common: created directory at: ./artifacts/prepare_base_model]
[2025-09-10 03:11:47,184: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-10 03:11:47,771: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-10 03:11:49,054: INFO: main: >>>>>> Prepare Base Model Phase completed <<<<<<

x==========x]
[2025-09-14 15:11:54,972: INFO: utils: NumExpr defaulting to 16 threads.]
[2025-09-14 15:11:57,263: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-14 15:11:57,269: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-14 15:11:57,271: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-14 15:11:57,273: INFO: common: created directory at: ./artifacts/prepare_base_model]
[2025-09-14 15:11:57,577: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-14 15:11:58,029: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-14 15:11:58,597: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-14 15:11:58,600: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-14 15:11:58,601: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-14 15:11:58,602: INFO: common: created directory at: artifacts/training]
[2025-09-14 15:11:58,763: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-09-14 15:13:36,554: INFO: utils: NumExpr defaulting to 16 threads.]
[2025-09-14 15:13:38,903: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-14 15:13:38,906: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-14 15:13:38,907: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-14 15:13:38,908: INFO: common: created directory at: ./artifacts/prepare_base_model]
[2025-09-14 15:13:39,207: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-14 15:13:39,566: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-14 15:13:40,123: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-14 15:13:40,126: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-14 15:13:40,128: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-14 15:13:40,129: INFO: common: created directory at: artifacts/training]
[2025-09-14 15:13:40,292: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-09-14 15:15:59,163: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-14 15:15:59,165: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-14 15:15:59,166: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-14 15:15:59,166: INFO: common: created directory at: ./artifacts/prepare_base_model]
[2025-09-14 15:15:59,422: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-14 15:15:59,904: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-14 15:16:09,040: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-14 15:16:09,043: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-14 15:16:09,043: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-14 15:16:09,044: INFO: common: created directory at: artifacts/training]
[2025-09-14 15:16:09,212: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-09-14 17:21:36,401: INFO: utils: NumExpr defaulting to 16 threads.]
[2025-09-14 17:21:44,586: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-14 17:21:44,619: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-14 17:21:44,622: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-14 17:21:44,623: INFO: common: created directory at: ./artifacts/prepare_base_model]
[2025-09-14 17:21:45,879: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-14 17:21:46,213: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-14 17:21:46,876: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-14 17:21:46,880: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-14 17:21:46,881: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-14 17:21:46,882: INFO: common: created directory at: artifacts/training]
[2025-09-14 17:21:47,031: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-09-14 17:45:45,777: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-14 18:07:55,266: INFO: main: >>>>>> Data Ingestion Phase started <<<<<<]
[2025-09-14 18:07:55,267: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-14 18:07:55,301: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-14 18:07:55,302: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-14 18:07:55,302: INFO: common: created directory at: ./artifacts/data_ingestion]
[2025-09-14 18:07:55,302: INFO: data_ingestion: Downloading file from :[https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing] into :[artifacts/data_ingestion/data.zip]]
[2025-09-14 18:08:19,570: INFO: data_ingestion: File :[artifacts/data_ingestion/data.zip] has been downloaded successfully.]
[2025-09-14 18:08:19,571: INFO: data_ingestion: Unzipping file :[artifacts/data_ingestion/data.zip] into dir :[artifacts/data_ingestion]]
[2025-09-14 18:08:20,784: INFO: data_ingestion: Unzipping completed successfully. and data is available at :[artifacts/data_ingestion]]
[2025-09-14 18:08:20,784: INFO: main: >>>>>> Data Ingestion Phase completed <<<<<<

x==========x]
[2025-09-14 18:08:20,784: INFO: main: >>>>>> Prepare Base Model Phase started <<<<<<]
[2025-09-14 18:08:20,789: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-14 18:08:20,793: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-14 18:08:20,793: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-14 18:08:20,794: INFO: common: created directory at: ./artifacts/prepare_base_model]
[2025-09-14 18:08:21,246: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-14 18:08:21,485: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-14 18:08:23,416: INFO: main: >>>>>> Prepare Base Model Phase completed <<<<<<

x==========x]
[2025-09-14 18:08:23,416: INFO: main: >>>>>> Model Training Phase started <<<<<<]
[2025-09-14 18:08:23,421: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-14 18:08:23,424: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-14 18:08:23,425: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-14 18:08:23,425: INFO: common: created directory at: artifacts/training]
[2025-09-14 18:08:23,543: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-09-14 18:13:59,924: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-14 18:14:00,146: INFO: main: >>>>>> Model Training Phase completed <<<<<<

x==========x]
[2025-09-24 16:13:14,003: INFO: main: >>>>>> Data Ingestion Phase started <<<<<<]
[2025-09-24 16:13:14,032: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-24 16:13:14,054: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-24 16:13:14,055: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-24 16:13:14,055: INFO: common: created directory at: ./artifacts/data_ingestion]
[2025-09-24 16:13:14,055: INFO: data_ingestion: Downloading file from :[https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing] into :[artifacts/data_ingestion/data.zip]]
[2025-09-24 16:13:38,040: INFO: data_ingestion: File :[artifacts/data_ingestion/data.zip] has been downloaded successfully.]
[2025-09-24 16:13:38,040: INFO: data_ingestion: Unzipping file :[artifacts/data_ingestion/data.zip] into dir :[artifacts/data_ingestion]]
[2025-09-24 16:13:38,939: INFO: data_ingestion: Unzipping completed successfully. and data is available at :[artifacts/data_ingestion]]
[2025-09-24 16:13:38,939: INFO: main: >>>>>> Data Ingestion Phase completed <<<<<<

x==========x]
[2025-09-24 16:13:38,939: INFO: main: >>>>>> Prepare Base Model Phase started <<<<<<]
[2025-09-24 16:13:38,941: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-24 16:13:38,942: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-24 16:13:38,942: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-24 16:13:38,942: INFO: common: created directory at: ./artifacts/prepare_base_model]
[2025-09-24 16:13:39,971: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-24 16:13:40,279: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-24 16:13:41,183: INFO: main: >>>>>> Prepare Base Model Phase completed <<<<<<

x==========x]
[2025-09-24 16:13:41,183: INFO: main: >>>>>> Model Training Phase started <<<<<<]
[2025-09-24 16:13:41,187: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-24 16:13:41,188: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-24 16:13:41,188: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-24 16:13:41,189: INFO: common: created directory at: artifacts/training]
[2025-09-24 16:13:41,275: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-09-24 16:19:07,366: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-24 16:19:07,712: INFO: main: >>>>>> Model Training Phase completed <<<<<<

x==========x]
[2025-09-24 16:25:51,199: INFO: main: >>>>>> Data Ingestion Phase started <<<<<<]
[2025-09-24 16:25:51,201: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-24 16:25:51,201: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-24 16:25:51,202: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-24 16:25:51,202: INFO: common: created directory at: ./artifacts/data_ingestion]
[2025-09-24 16:25:51,202: INFO: data_ingestion: Downloading file from :[https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing] into :[artifacts/data_ingestion/data.zip]]
[2025-09-24 16:26:15,180: INFO: data_ingestion: File :[artifacts/data_ingestion/data.zip] has been downloaded successfully.]
[2025-09-24 16:26:15,181: INFO: data_ingestion: Unzipping file :[artifacts/data_ingestion/data.zip] into dir :[artifacts/data_ingestion]]
[2025-09-24 16:26:16,460: INFO: data_ingestion: Unzipping completed successfully. and data is available at :[artifacts/data_ingestion]]
[2025-09-24 16:26:16,460: INFO: main: >>>>>> Data Ingestion Phase completed <<<<<<

x==========x]
[2025-09-24 16:26:16,460: INFO: main: >>>>>> Prepare Base Model Phase started <<<<<<]
[2025-09-24 16:26:16,462: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-24 16:26:16,462: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-24 16:26:16,462: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-24 16:26:16,462: INFO: common: created directory at: ./artifacts/prepare_base_model]
[2025-09-24 16:26:16,841: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-24 16:26:17,140: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-24 16:26:17,722: INFO: main: >>>>>> Prepare Base Model Phase completed <<<<<<

x==========x]
[2025-09-24 16:26:17,722: INFO: main: >>>>>> Model Training Phase started <<<<<<]
[2025-09-24 16:26:17,723: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-24 16:26:17,724: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-24 16:26:17,724: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-24 16:26:17,724: INFO: common: created directory at: artifacts/training]
[2025-09-24 16:26:17,813: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-09-24 16:31:41,868: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-24 16:31:42,140: INFO: main: >>>>>> Model Training Phase completed <<<<<<

x==========x]
[2025-09-24 16:31:42,141: INFO: main: >>>>>> MLflow Model Evaluation Phase started <<<<<<]
[2025-09-24 16:31:42,146: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-24 16:31:42,149: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-24 16:31:42,150: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-24 16:31:42,292: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-09-24 16:31:54,310: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "/home/yousef/Kidney-Diseases-Classification/main.py", line 44, in <module>
    obj.main()
    ~~~~~~~~^^
  File "/home/yousef/Kidney-Diseases-Classification/src/cnnClassifier/pipeline/Phase_03_mlflow_evalution.py", line 18, in main
    evaluation.log_into_mlflow()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/yousef/Kidney-Diseases-Classification/src/cnnClassifier/components/model_evaluation.py", line 73, in log_into_mlflow
    with mlflow.start_run(experiment_id=experiment.experiment_id):
         ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/tracking/fluent.py", line 474, in start_run
    active_run_obj = client.create_run(
        experiment_id=exp_id_for_run,
        tags=resolved_tags,
        run_name=run_name,
    )
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/tracking/client.py", line 442, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/telemetry/track.py", line 29, in wrapper
    result = func(*args, **kwargs)
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/tracking/_tracking_service/client.py", line 173, in create_run
    return self.store.create_run(
           ~~~~~~~~~~~~~~~~~~~~~^
        experiment_id=experiment_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        run_name=run_name,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/store/tracking/rest_store.py", line 271, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/store/tracking/rest_store.py", line 134, in _call_endpoint
    return call_endpoint(
        self.get_host_creds(),
    ...<4 lines>...
        retry_timeout_seconds=retry_timeout_seconds,
    )
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/utils/rest_utils.py", line 554, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/utils/rest_utils.py", line 314, in verify_rest_response
    raise MlflowException(
    ...<2 lines>...
    )
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2025-09-24 18:53:29,399: INFO: main: >>>>>> Data Ingestion Phase started <<<<<<]
[2025-09-24 18:53:29,401: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-24 18:53:29,402: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-24 18:53:29,402: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-24 18:53:29,402: INFO: common: created directory at: ./artifacts/data_ingestion]
[2025-09-24 18:53:29,402: INFO: data_ingestion: Downloading file from :[https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing] into :[artifacts/data_ingestion/data.zip]]
[2025-09-24 18:53:53,541: INFO: data_ingestion: File :[artifacts/data_ingestion/data.zip] has been downloaded successfully.]
[2025-09-24 18:53:53,541: INFO: data_ingestion: Unzipping file :[artifacts/data_ingestion/data.zip] into dir :[artifacts/data_ingestion]]
[2025-09-24 18:53:55,098: INFO: data_ingestion: Unzipping completed successfully. and data is available at :[artifacts/data_ingestion]]
[2025-09-24 18:53:55,098: INFO: main: >>>>>> Data Ingestion Phase completed <<<<<<

x==========x]
[2025-09-24 18:53:55,098: INFO: main: >>>>>> Prepare Base Model Phase started <<<<<<]
[2025-09-24 18:53:55,099: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-24 18:53:55,100: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-24 18:53:55,100: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-24 18:53:55,100: INFO: common: created directory at: ./artifacts/prepare_base_model]
[2025-09-24 18:53:55,305: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-24 18:53:55,965: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-24 18:53:56,853: INFO: main: >>>>>> Prepare Base Model Phase completed <<<<<<

x==========x]
[2025-09-24 18:53:56,853: INFO: main: >>>>>> Model Training Phase started <<<<<<]
[2025-09-24 18:53:56,860: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-24 18:53:56,864: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-24 18:53:56,864: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-24 18:53:56,865: INFO: common: created directory at: artifacts/training]
[2025-09-24 18:53:56,983: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-09-24 18:59:20,669: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-24 18:59:21,009: INFO: main: >>>>>> Model Training Phase completed <<<<<<

x==========x]
[2025-09-24 18:59:21,010: INFO: main: >>>>>> MLflow Model Evaluation Phase started <<<<<<]
[2025-09-24 18:59:21,015: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-24 18:59:21,018: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-24 18:59:21,018: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-24 18:59:21,149: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-09-24 18:59:32,697: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "/home/yousef/Kidney-Diseases-Classification/main.py", line 44, in <module>
    obj.main()
    ~~~~~~~~^^
  File "/home/yousef/Kidney-Diseases-Classification/src/cnnClassifier/pipeline/Phase_03_mlflow_evalution.py", line 18, in main
    evaluation.log_into_mlflow()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/yousef/Kidney-Diseases-Classification/src/cnnClassifier/components/model_evaluation.py", line 73, in log_into_mlflow
    with mlflow.start_run(experiment_id=experiment.experiment_id):
         ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/tracking/fluent.py", line 474, in start_run
    active_run_obj = client.create_run(
        experiment_id=exp_id_for_run,
        tags=resolved_tags,
        run_name=run_name,
    )
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/tracking/client.py", line 442, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/telemetry/track.py", line 29, in wrapper
    result = func(*args, **kwargs)
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/tracking/_tracking_service/client.py", line 173, in create_run
    return self.store.create_run(
           ~~~~~~~~~~~~~~~~~~~~~^
        experiment_id=experiment_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        run_name=run_name,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/store/tracking/rest_store.py", line 271, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/store/tracking/rest_store.py", line 134, in _call_endpoint
    return call_endpoint(
        self.get_host_creds(),
    ...<4 lines>...
        retry_timeout_seconds=retry_timeout_seconds,
    )
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/utils/rest_utils.py", line 554, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/utils/rest_utils.py", line 314, in verify_rest_response
    raise MlflowException(
    ...<2 lines>...
    )
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2025-09-24 19:05:04,367: INFO: main: >>>>>> Data Ingestion Phase started <<<<<<]
[2025-09-24 19:05:04,369: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-24 19:05:04,369: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-24 19:05:04,370: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-24 19:05:04,370: INFO: common: created directory at: ./artifacts/data_ingestion]
[2025-09-24 19:05:04,370: INFO: data_ingestion: Downloading file from :[https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing] into :[artifacts/data_ingestion/data.zip]]
[2025-09-24 19:05:28,835: INFO: data_ingestion: File :[artifacts/data_ingestion/data.zip] has been downloaded successfully.]
[2025-09-24 19:05:28,836: INFO: data_ingestion: Unzipping file :[artifacts/data_ingestion/data.zip] into dir :[artifacts/data_ingestion]]
[2025-09-24 19:05:30,792: INFO: data_ingestion: Unzipping completed successfully. and data is available at :[artifacts/data_ingestion]]
[2025-09-24 19:05:30,792: INFO: main: >>>>>> Data Ingestion Phase completed <<<<<<

x==========x]
[2025-09-24 19:05:30,793: INFO: main: >>>>>> Prepare Base Model Phase started <<<<<<]
[2025-09-24 19:05:30,795: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-24 19:05:30,796: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-24 19:05:30,797: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-24 19:05:30,797: INFO: common: created directory at: ./artifacts/prepare_base_model]
[2025-09-24 19:05:31,100: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-24 19:05:31,393: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-24 19:05:32,206: INFO: main: >>>>>> Prepare Base Model Phase completed <<<<<<

x==========x]
[2025-09-24 19:05:32,206: INFO: main: >>>>>> Model Training Phase started <<<<<<]
[2025-09-24 19:05:32,209: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-24 19:05:32,211: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-24 19:05:32,211: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-24 19:05:32,211: INFO: common: created directory at: artifacts/training]
[2025-09-24 19:05:32,382: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-09-24 19:14:46,069: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-24 19:14:46,288: INFO: main: >>>>>> Model Training Phase completed <<<<<<

x==========x]
[2025-09-24 19:14:46,288: INFO: main: >>>>>> MLflow Model Evaluation Phase started <<<<<<]
[2025-09-24 19:14:46,293: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-24 19:14:46,296: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-24 19:14:46,296: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-24 19:14:46,444: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-09-24 19:15:03,043: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "/home/yousef/Kidney-Diseases-Classification/main.py", line 44, in <module>
    obj.main()
    ~~~~~~~~^^
  File "/home/yousef/Kidney-Diseases-Classification/src/cnnClassifier/pipeline/Phase_03_mlflow_evalution.py", line 18, in main
    evaluation.log_into_mlflow()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/yousef/Kidney-Diseases-Classification/src/cnnClassifier/components/model_evaluation.py", line 73, in log_into_mlflow
    with mlflow.start_run(experiment_id=experiment.experiment_id):
         ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/tracking/fluent.py", line 474, in start_run
    active_run_obj = client.create_run(
        experiment_id=exp_id_for_run,
        tags=resolved_tags,
        run_name=run_name,
    )
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/tracking/client.py", line 442, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/telemetry/track.py", line 29, in wrapper
    result = func(*args, **kwargs)
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/tracking/_tracking_service/client.py", line 173, in create_run
    return self.store.create_run(
           ~~~~~~~~~~~~~~~~~~~~~^
        experiment_id=experiment_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        run_name=run_name,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/store/tracking/rest_store.py", line 271, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/store/tracking/rest_store.py", line 134, in _call_endpoint
    return call_endpoint(
        self.get_host_creds(),
    ...<4 lines>...
        retry_timeout_seconds=retry_timeout_seconds,
    )
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/utils/rest_utils.py", line 554, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/utils/rest_utils.py", line 314, in verify_rest_response
    raise MlflowException(
    ...<2 lines>...
    )
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2025-09-24 19:20:05,298: INFO: main: >>>>>> Data Ingestion Phase started <<<<<<]
[2025-09-24 19:20:05,300: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-24 19:20:05,301: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-24 19:20:05,301: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-24 19:20:05,302: INFO: common: created directory at: ./artifacts/data_ingestion]
[2025-09-24 19:20:05,302: INFO: data_ingestion: Downloading file from :[https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing] into :[artifacts/data_ingestion/data.zip]]
[2025-09-24 19:20:32,840: INFO: data_ingestion: File :[artifacts/data_ingestion/data.zip] has been downloaded successfully.]
[2025-09-24 19:20:32,841: INFO: data_ingestion: Unzipping file :[artifacts/data_ingestion/data.zip] into dir :[artifacts/data_ingestion]]
[2025-09-24 19:20:33,919: INFO: data_ingestion: Unzipping completed successfully. and data is available at :[artifacts/data_ingestion]]
[2025-09-24 19:20:33,919: INFO: main: >>>>>> Data Ingestion Phase completed <<<<<<

x==========x]
[2025-09-24 19:20:33,919: INFO: main: >>>>>> Prepare Base Model Phase started <<<<<<]
[2025-09-24 19:20:33,922: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-24 19:20:33,923: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-24 19:20:33,923: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-24 19:20:33,923: INFO: common: created directory at: ./artifacts/prepare_base_model]
[2025-09-24 19:20:34,167: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-24 19:20:34,851: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-24 19:20:35,592: INFO: main: >>>>>> Prepare Base Model Phase completed <<<<<<

x==========x]
[2025-09-24 19:20:35,593: INFO: main: >>>>>> Model Training Phase started <<<<<<]
[2025-09-24 19:20:35,596: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-24 19:20:35,597: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-24 19:20:35,597: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-24 19:20:35,597: INFO: common: created directory at: artifacts/training]
[2025-09-24 19:20:35,724: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-09-24 19:36:26,402: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-24 19:36:26,612: INFO: main: >>>>>> Model Training Phase completed <<<<<<

x==========x]
[2025-09-24 19:36:26,613: INFO: main: >>>>>> MLflow Model Evaluation Phase started <<<<<<]
[2025-09-24 19:36:26,618: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-24 19:36:26,620: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-24 19:36:26,621: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-24 19:36:26,769: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-09-24 19:36:37,074: ERROR: main: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: '']
Traceback (most recent call last):
  File "/home/yousef/Kidney-Diseases-Classification/main.py", line 44, in <module>
    obj.main()
    ~~~~~~~~^^
  File "/home/yousef/Kidney-Diseases-Classification/src/cnnClassifier/pipeline/Phase_03_mlflow_evalution.py", line 18, in main
    evaluation.log_into_mlflow()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/yousef/Kidney-Diseases-Classification/src/cnnClassifier/components/model_evaluation.py", line 73, in log_into_mlflow
    with mlflow.start_run(experiment_id=experiment.experiment_id):
         ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/tracking/fluent.py", line 474, in start_run
    active_run_obj = client.create_run(
        experiment_id=exp_id_for_run,
        tags=resolved_tags,
        run_name=run_name,
    )
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/tracking/client.py", line 442, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/telemetry/track.py", line 29, in wrapper
    result = func(*args, **kwargs)
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/tracking/_tracking_service/client.py", line 173, in create_run
    return self.store.create_run(
           ~~~~~~~~~~~~~~~~~~~~~^
        experiment_id=experiment_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        run_name=run_name,
        ^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/store/tracking/rest_store.py", line 271, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/store/tracking/rest_store.py", line 134, in _call_endpoint
    return call_endpoint(
        self.get_host_creds(),
    ...<4 lines>...
        retry_timeout_seconds=retry_timeout_seconds,
    )
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/utils/rest_utils.py", line 554, in call_endpoint
    response = verify_rest_response(response, endpoint)
  File "/home/yousef/miniconda3/lib/python3.13/site-packages/mlflow/utils/rest_utils.py", line 314, in verify_rest_response
    raise MlflowException(
    ...<2 lines>...
    )
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
[2025-09-24 21:03:43,492: INFO: main: >>>>>> Data Ingestion Phase started <<<<<<]
[2025-09-24 21:03:43,495: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-24 21:03:43,495: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-24 21:03:43,496: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-24 21:03:43,496: INFO: common: created directory at: ./artifacts/data_ingestion]
[2025-09-24 21:03:43,496: INFO: data_ingestion: Downloading file from :[https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing] into :[artifacts/data_ingestion/data.zip]]
[2025-09-24 21:04:07,341: INFO: data_ingestion: File :[artifacts/data_ingestion/data.zip] has been downloaded successfully.]
[2025-09-24 21:04:07,341: INFO: data_ingestion: Unzipping file :[artifacts/data_ingestion/data.zip] into dir :[artifacts/data_ingestion]]
[2025-09-24 21:04:08,730: INFO: data_ingestion: Unzipping completed successfully. and data is available at :[artifacts/data_ingestion]]
[2025-09-24 21:04:08,731: INFO: main: >>>>>> Data Ingestion Phase completed <<<<<<

x==========x]
[2025-09-24 21:04:08,731: INFO: main: >>>>>> Prepare Base Model Phase started <<<<<<]
[2025-09-24 21:04:08,733: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-24 21:04:08,734: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-24 21:04:08,735: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-24 21:04:08,735: INFO: common: created directory at: ./artifacts/prepare_base_model]
[2025-09-24 21:04:08,979: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-24 21:04:09,407: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-24 21:04:10,024: INFO: main: >>>>>> Prepare Base Model Phase completed <<<<<<

x==========x]
[2025-09-24 21:04:10,024: INFO: main: >>>>>> Model Training Phase started <<<<<<]
[2025-09-24 21:04:10,031: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-24 21:04:10,035: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-24 21:04:10,035: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-24 21:04:10,036: INFO: common: created directory at: artifacts/training]
[2025-09-24 21:04:10,175: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-09-24 21:13:01,293: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-24 21:13:01,632: INFO: main: >>>>>> Model Training Phase completed <<<<<<

x==========x]
[2025-09-24 21:13:01,633: INFO: main: >>>>>> MLflow Model Evaluation Phase started <<<<<<]
[2025-09-24 21:13:01,638: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-24 21:13:01,640: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-24 21:13:01,641: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-24 21:13:01,784: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-09-24 21:22:42,827: INFO: main: >>>>>> MLflow Model Evaluation Phase completed <<<<<<

x==========x]
[2025-09-28 14:22:43,551: INFO: Phase_00_data_ingestion: >>>>>> Data Ingestion Phase started <<<<<<]
[2025-09-28 14:22:43,580: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-28 14:22:43,603: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-28 14:22:43,603: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-28 14:22:43,604: INFO: common: created directory at: ./artifacts/data_ingestion]
[2025-09-28 14:22:43,604: INFO: data_ingestion: Downloading file from :[https://drive.google.com/file/d/1vlhZ5c7abUKF8xXERIw6m9Te8fW7ohw3/view?usp=sharing] into :[artifacts/data_ingestion/data.zip]]
[2025-09-28 14:23:08,085: INFO: data_ingestion: File :[artifacts/data_ingestion/data.zip] has been downloaded successfully.]
[2025-09-28 14:23:08,086: INFO: data_ingestion: Unzipping file :[artifacts/data_ingestion/data.zip] into dir :[artifacts/data_ingestion]]
[2025-09-28 14:23:08,474: INFO: data_ingestion: Unzipping completed successfully. and data is available at :[artifacts/data_ingestion]]
[2025-09-28 14:23:08,474: INFO: Phase_00_data_ingestion: >>>>>> Data Ingestion Phase completed <<<<<<

x==========x]
[2025-09-28 14:25:58,844: INFO: Phase_01_prepare_base_model: >>>>>> Prepare Base Model Phase started <<<<<<]
[2025-09-28 14:25:58,852: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-28 14:25:58,856: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-28 14:25:58,857: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-28 14:25:58,857: INFO: common: created directory at: ./artifacts/prepare_base_model]
[2025-09-28 14:25:59,892: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-28 14:25:59,976: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-28 14:26:00,035: INFO: Phase_01_prepare_base_model: >>>>>> Prepare Base Model Phase completed <<<<<<

x==========x]
[2025-09-28 14:26:04,001: INFO: Phase_02_model_training: >>>>>>>>>> Stage Model Training Stage started <<<<<<<<<<]
[2025-09-28 14:26:04,003: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-28 14:26:04,004: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-28 14:26:04,005: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-28 14:26:04,005: INFO: common: created directory at: artifacts/training]
[2025-09-28 14:26:04,184: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-09-28 14:32:56,308: WARNING: saving_api: You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`. ]
[2025-09-28 14:32:56,391: INFO: Phase_02_model_training: >>>>>>>>>> Stage Model Training Stage completed <<<<<<<<<<

x==========x]
[2025-09-28 15:57:41,619: INFO: Phase_03_mlflow_evalution: >>>>>>>>>> Stage MLflow Model Evaluation Stage started <<<<<<<<<<]
[2025-09-28 15:57:41,621: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-28 15:57:41,622: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-28 15:57:41,622: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-28 15:57:41,805: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-09-28 16:07:17,126: INFO: Phase_03_mlflow_evalution: >>>>>>>>>> Stage MLflow Model Evaluation Stage completed <<<<<<<<<<

x==========x]
[2025-09-28 16:07:56,686: INFO: Phase_03_mlflow_evalution: >>>>>>>>>> Stage MLflow Model Evaluation Stage started <<<<<<<<<<]
[2025-09-28 16:07:56,688: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-28 16:07:56,689: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-28 16:07:56,689: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-28 16:07:56,883: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-09-28 16:18:15,525: INFO: Phase_03_mlflow_evalution: >>>>>>>>>> Stage MLflow Model Evaluation Stage completed <<<<<<<<<<

x==========x]
[2025-09-28 16:43:42,334: INFO: Phase_03_mlflow_evalution: >>>>>>>>>> Stage MLflow Model Evaluation Stage started <<<<<<<<<<]
[2025-09-28 16:43:42,336: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/configs/config.yaml loaded successfully]
[2025-09-28 16:43:42,336: INFO: common: yaml file: /home/yousef/Kidney-Diseases-Classification/params.yaml loaded successfully]
[2025-09-28 16:43:42,337: INFO: common: created directory at: /home/yousef/Kidney-Diseases-Classification/artifacts]
[2025-09-28 16:43:42,474: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2025-09-28 16:53:12,318: INFO: Phase_03_mlflow_evalution: >>>>>>>>>> Stage MLflow Model Evaluation Stage completed <<<<<<<<<<

x==========x]
